name: Docker Push

on:
  workflow_run:
    workflows: [ "🎉post-release" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Get Github tag
        id: meta
        shell: bash
        run: |
          curl --silent "https://api.github.com/repos/cn-kali-team/notion-rss/releases/latest" > latest.json
          cat latest.json| jq -r .tag_name | xargs -I {} echo TAG={} >> $GITHUB_ENV
          cat latest.json| jq -r '.assets[]|select(.name |startswith("notion-rss-cli_"))|select(.name |endswith("unknown-linux-musl.tar.gz")).browser_download_url' | xargs -I {} echo DOWNLOAD_URL={} >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            DOWNLOAD_URL=${{ steps.meta.env.DOWNLOAD_URL }}
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/notion-rss:latest,${{ secrets.DOCKER_USERNAME }}/notion-rss:${{ steps.meta.env.TAG }}